[package]
name = "tidefram"
version = "0.1.0"
authors = ["daozhu <daozhu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.8.1"
async-std = { version = "1.5.0", features = ["attributes"] }